import Head from "next/head";
import Image from "next/image";
import { createClient } from "next-sanity";
import imageUrlBuilder from "@sanity/image-url";
import Link from "next/link";
import TheHeader from "../components/Theheader";

export default function Home({ posts }) {
  const builder = imageUrlBuilder(client);

  function urlFor(source) {
    return builder.image(source);
  }

  return (
    <div className="text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TheHeader />

      <main className="my-10 max-w-6xl mx-auto grid gap-6 grid-cols-1 lg:grid-cols-2">
        {posts.map((post) => (
          <Link key={post._id} href={`post/${post.slug.current}`}>
            <div className="max-w-2xl mx-auto overflow-hidden bg-gray-900 rounded-lg shadow-md">
              <img
                className="object-cover w-full h-64"
                src={urlFor(post.mainImage)}
                alt={post.title}
              />

              <div className="p-6">
                <div>
                  {post.categories?.map((category) => (
                    <span
                      key={category._key}
                      className="text-xs font-medium text-blue-600 uppercase hover:text-blue-500 cursor-pointer"
                    >
                      {category.name} &nbsp;
                    </span>
                  ))}
                  <Link
                    href={`post/${post.slug.current}`}
                    className="block mt-2 text-2xl font-semibold text-gray-800 transition-colors duration-200 transform dark:text-white hover:text-gray-600 hover:underline"
                  >
                    {post.title}
                  </Link>
                  <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Beatae, mollitia. Lorem ipsum dolor sit amet consectetur
                    adipisicing elit. Odio, dolores!
                  </p>
                </div>

                <div className="mt-4">
                  <div className="flex items-center">
                    <div className="flex items-center">
                      <img
                        className="object-cover h-10 rounded-full"
                        src={urlFor(post.author.image)}
                        alt={post.author.name}
                      />
                      <Link
                        href="/"
                        className="mx-2 font-semibold text-gray-700 dark:text-gray-200"
                      >
                        {post.author.name}
                      </Link>
                    </div>
                    <span className="mx-1 text-xs text-gray-600 dark:text-gray-300">
                      {post._createdAt}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </Link>
        ))}
      </main>
    </div>
  );
}

const client = createClient({
  projectId: "r0riooy5",
  dataset: "production",
  apiVersion: "2022-07-15",
  useCdn: false,
});

export async function getServerSideProps() {
  const posts = await client.fetch(`*[_type == "post"]{
    _id,
    title,
    slug,
    _createdAt,
    body,
    mainImage,
    author->{
        name,
        image
      }, 
    categories[] -> {
      _key,
      name
    }
  }`);

  return {
    props: {
      posts,
    },
  };
}
